site/CAMPlive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

urlpatterns = [
    path(settings.URL_PREFIX + "admin/", admin.site.urls),
    path(settings.URL_PREFIX + 'accounts/', include('allauth.urls')),
    path(settings.URL_PREFIX, include('camplive.urls'))
]

if settings.DEBUG: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/camplive/urls.py
from django.urls import path
from . import views
from . import signals

urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login, name = "login"),
    path("logout", views.deconnexion, name = "logout"),
    path("creer-camp", views.paramCamp, name = "creer-camp"),
    path("modifier-camp-<int:idcamp>", views.paramCamp, name = "modifier-camp"),
    path("camp/<int:idcamp>/<slug:slug>", views.camp, name = "camp"),
    path("camp/<int:idcamp>/<slug:slug>/abonnement", views.inscriptionNewsletter, name = "inscription-newsletter"),
    path("camp/<int:idcamp>/<slug:slug>/confirmabonnement-<int:idabo>-<str:token>", views.inscriptionNewsletter, name = "confirmation-newsletter"),
    path("admincamp-<int:idcamp>", views.adminCamp, name = "adminCamp"),
    path("supprcamp-<int:idcamp>", views.supprCamp, name = "supprCamp"),
    path("gestionajout-<int:idcamp>", views.gestionAjout, name = "gestionAjout"),
    path("gestionajoutrappel-<int:idgestionajout>", views.gestionAjoutRappel, name = "gestionAjoutRappel"),
    path("gestionmodif-<int:idgestion>", views.gestionModif, name = "gestionModif"),
    path("gestionsuppr-<int:idgestion>", views.gestionSuppr, name = "gestionSuppr"),
    path("confirmationgestion/<int:idcamp>/<str:token>", views.gestionAjout, name = "confirmation-gestion"),
    path("message-<int:idcamp>", views.message, name = "creer-message"),
    path("modifier-message-<int:idcamp>-<int:idmessage>", views.message, name = "modifier-message"),
    path("supprimer-message-<int:idcamp>-<int:idmessage>", views.supprimerMessage, name = "supprimer-message"),
    path("photo-<int:idcamp>", views.photo, name = "creer-photo"),
    path("download-<int:idcamp>", views.exportZIP, name = "exportZIP"),
    path("supprimer-photo-<int:idcamp>-<int:idphoto>", views.supprimerPhoto, name = "supprimer-photo"),
]

site/camplive/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify
from django.conf import settings


# Create your models here.
class User(AbstractUser):
    pass

    def __str__(self):
        if self.first_name and self.last_name:
            return "{} {}".format(self.first_name, self.last_name)
        else:
            return self.username

class Camp(models.Model):
    titre = models.CharField(max_length = 50, verbose_name = "titre", help_text = "Indiquer le groupe, les unités et le lieu du camp")
    slug = models.SlugField(max_length = 50, verbose_name = "slug", null = True, blank = True)
    intro = models.TextField(verbose_name = "introduction", help_text = "Texte affiché en haut de page, pour présenter brièvement le camp", blank = True, null = True)
    debut = models.DateField(verbose_name = "premier jour du camp", help_text = "Format : jj/mm/aaaa")
    fin = models.DateField(verbose_name = "dernier jour du camp", help_text = "Format : jj/mm/aaaa")
    autoinscription = models.BooleanField(verbose_name = "inscriptions autonomes à la newsletter", help_text = "cocher pour permettre aux familles de s'inscrire de manière autonome à la newsletter", default = True)
    last_newsletter = models.DateTimeField(verbose_name = "date de la dernière newsletter", null = True, blank = True)
    created_by = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, blank = True, related_name = "creator")
    created_time = models.DateTimeField(auto_now_add = True)
    updated_by = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, blank = True, related_name = "updator")
    updated_time = models.DateTimeField(auto_now = True)
    
    class Meta:
        ordering = ['-debut', '-fin']
        models.CheckConstraint(check = models.Q(fin__gt = models.F('debut')), name = "check_debut_fin")
    
    def __str__(self):
        return "{} (du {}/{}/{} au {}/{}/{})".format(self.titre, self.debut.day, self.debut.month, self.debut.year, self.fin.day, self.fin.month, self.fin.year)
    
    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.titre)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("camp", kwargs={"idcamp": self.id, "slug": self.slug})

class Gestion(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "utilisateur")
    camp = models.ForeignKey(Camp, on_delete = models.CASCADE, verbose_name = "camp")
    droit = models.CharField(max_length = 20, choices = settings.DROITS, verbose_name = "droit")
    
    class Meta:
        ordering = ['camp', 'droit', 'user']
        models.UniqueConstraint(fields = ['user', 'camp'], name = "gestion_unique_user_camp")
    
    def __str__(self):
        return '{} est {} du camp "{}"'.format(self.user, self.droit, self.camp)

class GestionAjout(models.Model):
    camp = models.ForeignKey(Camp, on_delete = models.CASCADE, verbose_name = "camp")
    mail = models.EmailField(verbose_name = "adresse électonique")
    droit = models.CharField(max_length = 20, choices = settings.DROITS, verbose_name = "droit")
    token = models.CharField(max_length = 64, verbose_name = "token", null = True)
    created_by = models.ForeignKey(User, on_delete = models.CASCADE)
    created_time = models.DateTimeField(auto_now_add = True)
    
    class Meta:
        ordering = ['-created_time']
        models.UniqueConstraint(fields = ['mail', 'camp'], name = "gestionajout_unique_mail_camp")
    
    def __str__(self):
        return 'Ajout d\'un(e) {} au camp "{}"'.format(self.get_droit_display(), self.camp)

class Publication(models.Model):
    camp = models.ForeignKey(Camp, on_delete = models.CASCADE, verbose_name = "Camp")
    created_by = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, related_name = "%(app_label)s_%(class)s_creator")
    created_time = models.DateTimeField(auto_now_add = True)
    updated_by = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, related_name = "%(app_label)s_%(class)s_updator")
    updated_time = models.DateTimeField(auto_now = True)
    
    class Meta:
        abstract = True
        ordering = ['-updated_time']

class Message(Publication):
    texte = models.TextField(verbose_name = "message")
    
    def __str__(self):
        return "Message du {} du camp \"{} \"".format(self.updated_time.strftime("%d/%m/%Y %H:%I"), self.camp)

def chemin_photo_image(instance, fichier):
    return "photos/camp-{}/{}".format(instance.camp.id, fichier)

def chemin_photo_miniature(instance, fichier):
    return "photos/miniatures/camp-{}/{}".format(instance.camp.id, fichier)

class Photo(Publication):
    image = models.ImageField(upload_to = chemin_photo_image, height_field = "image_height", width_field = "image_width", verbose_name = "fichier image")
    image_height = models.IntegerField(verbose_name = "hauteur de l'image")
    image_width = models.IntegerField(verbose_name = "largeur de l'image")
    miniature = models.ImageField(upload_to = chemin_photo_miniature, height_field = "miniature_height", width_field = "miniature_width", verbose_name = "fichier miniature")
    miniature_height = models.IntegerField(verbose_name = "hauteur de la miniature")
    miniature_width = models.IntegerField(verbose_name = "largeur de la miniature")
    
    def __str__(self):
        return "Photo du {} du camp \"{} \"".format(self.updated_time.strftime("%d/%m/%Y %H:%I"), self.camp)

class AbonnementNewsletter(models.Model):
    camp = models.ForeignKey(Camp, on_delete = models.CASCADE, verbose_name = "Camp")
    mail = models.EmailField(verbose_name = "Adresse électronique")
    date = models.DateTimeField(auto_now_add = True)
    statut = models.CharField(max_length = 20, choices = settings.STATUTS_ABO_NEWSLETTER, verbose_name = "statut")
    token = models.CharField(max_length = 64, verbose_name = "token", null = True)
    
    class Meta:
        models.UniqueConstraint(fields = ['camp', 'mail'], name = "abonewsletter_unique_mail_camp")
        ordering = ['-date']
    
    def __str__(self):
        return "Abonnement de {} au camp \"{}\"".format(self.mail, self.camp)

site/camplive/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class DateInput(forms.DateInput):
    input_type = 'date'

class CampForm(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ['titre', 'debut', 'fin', 'intro', 'autoinscription']
    
    def clean_fin(self):
        debut = self.cleaned_data['debut']
        fin = self.cleaned_data['fin']
        if fin < debut:
            raise ValidationError("La date de fin doit être postérieure à la date de début.")
        return fin

class GestionAjoutForm(forms.ModelForm):
    class Meta:
        model = GestionAjout
        fields = ['mail', 'droit']

class GestionModifForm(forms.ModelForm):
    class Meta:
        model = Gestion
        fields = ['droit']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['texte']
        widgets = {'texte': forms.Textarea(attrs={'placeholder': "Écrire un message"})}
    
    def clean_texte(self):
        message = self.cleaned_data['texte'].strip()
        if len(message) == 0: raise ValidationError("Le message ne peut pas être vide.")
        return message

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class PhotoForm(forms.Form):
    image = MultipleFileField()

class AbonnementNewsletterForm(forms.ModelForm):
    class Meta:
        model = AbonnementNewsletter
        fields = ['mail']
        widgets = {'mail': forms.EmailInput(attrs={'placeholder': "Saisir une adresse électronique"})}

site/camplive/templates/camplive/accueil.html
{% extends "camplive/base.html" %}
{% load static %}

{% block separtitle %}{% endblock %}

{% block content %}
<div class = "mx-auto text-center">
<img src = "{% static 'camplive/css/img/logo.png' %}" alt = "logo" width = "75%"/>
<p class = "fs-2">
<span class = "fw-bold">CAMPlive</span> est un outil permettant une diffusion facilitée de messages et photos durant un camp. Les familles des participants peuvent ainsi à tout moment (et gratuitement) consulter les nouvelles du séjour ; elles ont même la possilibité de s'inscrire à une newsletter les avertissant d'une nouvelle publication.</p>
<p class = "fs-2">Si vous êtes une famille, vous devez disposer d'un lien fourni par l'organisateur du camp pour accéder aux messages et photos. Si vous êtes un organisateur, vous devez vous <a href="{% url 'login' %}">authentifier</a> via votre compte <a href = "https://galilee.eedf.fr">Galilée</a> afin d'utiliser ce service.</p>
</div>
<hr class = "border border-3 border-primary">

<h3>Fonctionnalités</h3>
<ul class = "fs-5">
<li>Publications de messages de longueur illimitée</li>
<li>Publications de photos par envois groupés (jusqu'à 100 par envoi)</li>
<li>Lien secret à partager aux personnes autorisées à consulter les publications (pas besoin de s'inscrire ou d'avoir un compte Galilée)</li>
<li>Envoi automatique d'une newsletter dans l'heure suivant la dernière publication</li>
<li>Inscription autonome des visiteurs à la newsletter (désactivation possible)</li>
<li>
Deux types de gestionnaire :
<ul>
<li>contributeur(trice) : peut publier/éditer/supprimer des messages, peut publier/supprimer des photos, peut télécharger une archive ZIP contenant tous les messages et photos</li>
<li>administrateur(trice) : détient les droits du rôle précédent + peut nommer/supprimer d'autres gestionnaires, modifier/supprimer la page, voir la liste des inscrits à la newsletter</li>
</ul>
</li>
</ul>
{% endblock %}

site/camplive/templates/camplive/admin_camp.html
{% extends "camplive/base.html" %}
{% load static %}

{% block title %}{{camp.titre}}{% endblock %}

{% block content %}
<h1>{{camp.titre}}</h1>
<h3>Informations générales</h3>
<p>
<i class="bi bi-calendar-date-fill text-success"></i> <strong>Début du camp</strong> {{ camp.debut|date:"l d F Y" }}<br/>
<i class="bi bi-calendar-date-fill text-danger"></i> <strong>Fin du camp</strong> {{ camp.fin|date:"l d F Y" }}<br/>
<i class="bi bi-newspaper text-warning"></i> <strong>Auto-inscription à la newsletter</strong> {% if camp.autoinscription %}autorisée{% else %}interdite{% endif %}<br/>
<i class="bi bi-link-45deg"></i> <strong>Lien à partager aux familles</strong> <a href = "{{camp.get_absolute_url}}">{{request.scheme}}://{{ request.get_host }}{{camp.get_absolute_url}}</a>
</p>
<p>
{% if droitgestion == "admin" %}
<a role="button" class="btn btn-primary" href = "{% url 'modifier-camp' idcamp=camp.id %}"><i class="bi bi-gear"></i><span class = "d-md-inline d-none"> Paramétrer le camp</span></a>
{% endif %}
<a role = "button" class = "btn btn-primary" href = "{% url 'exportZIP' idcamp=camp.id %}"><i class="bi bi-download"></i><span class = "d-md-inline d-none"> Télécharger les publications</span></a>
</p>

<h3>Gestionnaires</h3>
<p>
{% for gestion in gestions %}
<div class = "d-inline-block"><i class="bi bi-person droit-color-{{gestion.droit}}"></i> {% if droitgestion == "admin" and gestion.user != request.user %}<a href = "{% url 'gestionModif' idgestion=gestion.id %}">{% endif %}{{gestion.user}}{% if droitgestion == "admin" and gestion.user != request.user %}</a>{% endif %} <span class = "droit-tag droit-tag-{{gestion.droit}}">{{gestion.get_droit_display|capfirst}}</span></div>
{% endfor %}
</p>
{% if droitgestion == "admin" %}
{% if gestionAjouts.exists %}
<div>
<strong>Invitations</strong> 
{% for gestionAjout in gestionAjouts %}
<div class = "d-inline-block"><i class="bi bi-person text-light"></i> {{gestionAjout.mail}} ({{gestionAjout.get_droit_display|capfirst}}) <a role="button" class="btn btn-primary" title="Renvoyer un message d'invitation" href = "{% url 'gestionAjoutRappel' idgestionajout=gestionAjout.id %}"><i class="bi bi-arrow-clockwise"></i></a></div>
{% endfor %}
</div>
{% endif %}
<p>
<a role="button" class="btn btn-success" href = "{% url 'gestionAjout' idcamp=camp.id %}"><i class="bi bi-person-add"></i> Ajouter un(e) gestionnaire</a>
</p>
{% endif %}

<h3>Abonné(e)s à la newsletter</h3>
{% if camp.last_newsletter %}<p>Dernière newsletter envoyée le {{camp.last_newsletter|date:'l d F Y à H:i'}}</p>{% endif %}
{% if abonnes.count > 0 %}

{% regroup abonnes by statut as statuts_list %}
{% for statut, abonnes_list in statuts_list %}
<div>
{% if statut == "confirm" %}
<strong>en attente de confirmation ({{abonnes_list|length}})</strong> 
{% else %}
<strong>abonné(e){{abonnes_list|length|pluralize}} ({{abonnes_list|length}})</strong>  
{% endif %}
{% if droitgestion == "admin" %}
{% for abonne in abonnes_list %}
<div class = "d-inline-block"><i class="bi bi-envelope-at {% if abonne.statut == "confirm" %}text-warning{% else %}text-success{% endif %}"></i> {{abonne.mail}}</div>
{% endfor %}
{% endif %}
<div>
{% endfor %}
{% else %}
<p>Pas d'abonné à la newsletter pour le moment</p>
{% endif %}

<h3>Messages publiés</h3>
<form class = "mt-3 mb-3 bg-warning-subtle p-3" method = "post" action = "{% url 'creer-message' idcamp=camp.id %}">
<h4>Ajouter un message</h4>
{% csrf_token %}
<p>{{ message_form.texte }}</p> <input class="btn btn-primary" type="submit" value="Poster le message">
</form>
{% if publi_messages.count > 0 %}
<table>
{% for mess in publi_messages %}
<tr>
<td>{{mess.created_time|date:"d/m H:i"}}</td>
<td>{{mess.created_by}}</td>
<td>
<p class = "m-0">{{mess.texte|truncatechars:45}}</p>
{% if mess.updated_by %}
<p class = "m-0 fs-6 text-primary">édité par {{mess.updated_by}} le {{mess.updated_time|date:"d/m à H:i"}}</p>
{% endif %}
</td>
<td class = "text-end">
<a role="button" class="btn btn-warning" href = "{% url 'modifier-message' idcamp=camp.id idmessage=mess.id %}"><i class="bi bi-pencil-fill"></i><span class = "d-md-inline d-none"> Éditer</span></a>
<div onclick = "confirmerSupp('Voulez-vous vraiment supprimer ce message ?', '{% url 'supprimer-message' idcamp=camp.id idmessage=mess.id %}')" role="button" class="btn btn-danger"><i class="bi bi-x-circle"></i><span class = "d-md-inline d-none"> Supprimer</span></div>
</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>Aucun message posté.</p>
{% endif %}
<h3>Photos postées</h3>
<form class = "mt-3 mb-3 bg-warning-subtle p-3" method = "post" enctype='multipart/form-data' action = "{% url 'creer-photo' idcamp=camp.id %}">
<h4>Ajouter des photos</h4>
{% csrf_token %}
<p>{{ photo_form.image }}</p> <input class="btn btn-primary" type="submit" value="Poster les photos">
</form>
{% if publi_photos.count > 0 %}
<table>
{% for photo in publi_photos %}
<tr>
<td>{{photo.updated_time|date:"d/m H:i"}}</td>
<td>{% if photo.updated_by %}{{photo.updated_by}}{% else %}{{photo.created_by}}{% endif %}</td>
<td style = "height:50px"><img class = "img-fluid img-thumbnail" src = "{{photo.miniature.url}}" style = "max-height:100px"/></td>
<td class = "text-end"><div onclick = 'confirmerSupp("Voulez-vous vraiment supprimer cette photo ?", "{% url 'supprimer-photo' idcamp=camp.id idphoto=photo.id %}")' role="button" class="btn btn-danger"><i class="bi bi-x-circle"></i><span class = "d-md-inline d-none"> Supprimer</span></div></td>
</tr>
{% endfor %}
</table>
{% else %}
<p>Aucune photo postée.</p>
{% endif %}
{% endblock %}

site/camplive/templates/camplive/base.html
{% load static socialaccount %}
<!DOCTYPE html>
<html lang="fr">
<head>
	<title>{% block title %}{% endblock %}{% block separtitle %} | {% endblock %}CAMPlive</title>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta name="Description" content="CAMPlive, des photos et des nouvelles des camps éclés"/>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
	<link rel="stylesheet" media="screen" type="text/css" title="Design" href="{% static 'camplive/css/style.css'%}" />
	<link rel="shortcut icon" href="{% static 'camplive/css/img/favicon.ico'%}" />
	<link rel="image_src" href="{% static 'camplive/css/img/logo.png'%}"/>
	<meta property="og:title" content="" />
	<meta property="og:image" content="{% static 'camplive/css/img/logo.png'%}" />
	<meta property="og:description" content="CAMPlive, des photos et des nouvelles des camps éclés" />
	{% block inclusionhead %}{% endblock %}
</head>

<body class="min-vh-100 d-flex flex-column justify-content-between">
<section class = "container-fluid p-0">
<header class="container-fluid bg-light bg-gradient shadow sticky-top">
{% if request.user.is_authenticated %}
<nav class="container navbar navbar-light navbar-expand-lg">
{% else %}
<nav class="container navbar navbar-light navbar-expand">
{% endif %}
<a class="navbar-brand" href="{% url 'index' %}" id="logo"><img src = "{% static 'camplive/css/img/logo.png' %}" alt = "logo" height = "75"/></a><p class = "mb-0 fw-bold d-md-inline d-none">Des nouvelles et des photos<br/>en direct des camps organisés par des éclés</p>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
<ul class="navbar-nav">
{% if request.user.is_authenticated %}
<li class="nav-item">
<a class="nav-link" role="button" href="{% url 'index' %}" >Mes camps</a>
</li>
{% if request.user.is_superuser %}
<a class="nav-link" role="button" href="{% url 'admin:index' %}" >Administration</a>
{% endif %}
<li class="nav-item">
<form class="m-0" method="post" action="{% url 'account_logout' %}">
{% csrf_token %}
<a class="nav-link" role="button" onclick="this.closest('form').submit();" href="#">Déconnexion</a>
</form>
</li>
{% else %}
<li class="nav-item">
<form class="m-0" method="post" action="{% provider_login_url "keycloak" process="login" %}">
{% csrf_token %}
<a class="nav-link" onclick="this.closest('form').submit();" href="#">Connexion</a>
</form>
</li>
{% endif %}
</ul>
</div>
</nav>
</header>

<section id="content" class="container mt-3">
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"">{{ message }} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
    {% endfor %}
</div>
{% endif %}

{% block content %}{% endblock %}

</section>
</section>

<footer class="bg-primary bg-gradient mt-3 py-4">
<div class="container">
© CAMPlive<br/>
Un service de <a href = "https://galilee.eedf.fr">Galilée</a> proposé pour les adhérent(e)s <a href = "https://www.eedf.fr">EEDF</a>.
</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script type="text/javascript">
function confirmerSupp(message,lien){
	if (confirm(message)) {
		document.location.href=lien;
	}
}
</script>
</body>
</html>

site/camplive/templates/camplive/creer_camp.html
{% extends "camplive/base.html" %}
{% load static %}

{% block title %}{% if modif %}Modifier{% else %}Créer{% endif %} un camp{% endblock %}

{% block content %}
<h1>{% if modif %}Modifier{% else %}Créer{% endif %} un camp</h1>
<form method = "post">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-primary" type="submit" value="{% if modif %}Modifier{% else %}Créer{% endif %} le camp">
{% if modif %} <div onclick = 'confirmerSupp("Voulez-vous vraiment supprimer le CAMPlive de ce camp ?", "{% url 'supprCamp' idcamp=form.instance.id %}")' role="button" class="btn btn-danger"><i class="bi bi-x-circle"></i> Supprimer le camp</div>{% endif %}
</form>
{% endblock %}

site/camplive/templates/camplive/dashboard.html
{% extends "camplive/base.html" %}
{% load static %}

{% block title %}Mes camps{% endblock %}

{% block content %}
<h1>Mes camps</h1>
<a role="button" class="btn btn-success" href = {% url 'creer-camp' %}>Créer un camp</a>
{% for cat in camps %}
{% if cat.list.exists %}
<h3>{% if cat.list.count > 1 %}{{ cat.labelp }}{% else %}{{ cat.labels }}{% endif %}</h3>
<table>
<thead>
<th>Dénomination du camp</th><th></th><th>Début</th><th>Fin</th>
</thead>
{% for camp in cat.list %}
<tr>
<td><a href = {% url 'adminCamp' idcamp=camp.id %}>{{camp.titre}}</a>{% if camp.gestion.exists %} <span class = "droit-tag droit-tag-{{camp.gestion.first.droit}}">{{camp.gestion.first.get_droit_display|capfirst}}</span>{% endif %}</td>
<td><i class="bi bi-chat-left-dots-fill"></i>&nbsp;{{camp.message_set.all.count}} <i class="bi bi-file-earmark-image-fill"></i>&nbsp;{{camp.photo_set.all.count}} <i class="bi bi-envelope-at-fill"></i>&nbsp;{{camp.abonnementnewsletter_set.all.count}}</td>
<td>{{camp.debut|date:"d F Y"}}</td>
<td>{{camp.fin|date:"d F Y"}}</td>
</tr>
{% endfor %}
</table>
{% endif %}
{% endfor %}
{% endblock %}

site/camplive/templates/camplive/gestion_ajout.html
{% extends "camplive/base.html" %}
{% load static %}

{% block title %}Inviter à la gestion de "{{camp}}"{% endblock %}

{% block content %}
<h1>Inviter à la gestion de "{{camp}}"</h1>
<p>Cette page vous permet d'inviter par message électronique une personne à devenir administrateur(trice) ou contributeur(trice) de votre page CAMP live.</p>
<p class = "text-warning"><strong><i class="bi bi-exclamation-triangle-fill"></i> Attention :</strong> Seuls les détenteurs d'un compte Galilée pourront valider l'invtation.</p>
<form method = "post">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-primary" type="submit" value="Inviter">
</form>
{% endblock %}

site/camplive/templates/camplive/gestion_modif.html
{% extends "camplive/base.html" %}
{% load static %}

{% block title %}Droits du gestionnaires {{fgestion.user}}"{% endblock %}

{% block content %}
<h1>Droits du gestionnaires {{gestion.user}}</h1>
<form method = "post">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-primary" type="submit" value="Modifier les droits"> <div onclick='confirmerSupp("Voulez-vous vraiment supprimer les droits de gestion à {{gestion.user}} ?", "{% url 'gestionSuppr' idgestion=gestion.id %}")' role="button" class="btn btn-danger"><i class="bi bi-x-circle"></i> Supprimer les droits de gestion à {{gestion.user}}</div>
</form>
{% endblock %}